# Build docker image for rust hot-reloading via cargo-watch
FROM rust:1.67.1

# Volume Mount project dir at /app
WORKDIR /app

# Install cargo-watch (with layer cacheing)
RUN --mount=type=cache,target=/usr/local/cargo/registry \
  cargo install cargo-watch

# Copy initial source files
COPY ./ ./

# Set entrypoint for image
CMD ["cargo", "watch", "-x", "run"]
