on:
  push:
    branches:
      - dev

name: Dev

jobs:
  build-and-release:
    name: Build and Release (dev)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm32v7,linux/arm64v8
          push: true
          pull: true
          tags: nosduco/nforwardauth:dev,nosduco/nforwardauth:${{ github.ref_name }}
