on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Prepare Release

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: nforwardauth
          pull-request-header: Prepared release-type
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Bug Fixes"},{"type":"doc","section":"Documentation"},{"type":"perf","section":"Performance"},{"type":"refactor","section":"Refactor"},{"type":"test","section":"Testing"},{"type":"chore","section":"Miscellaneous Tasks"},{"type":"ci","section":"CI/CD"}]'
